create table if not exists admins
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) not null,
    email         varchar(255) not null
        constraint uk47bvqemyk6vlm0w7crc3opdd4
            unique,
    is_active     boolean      not null,
    last_login    timestamp(6),
    name          varchar(255) not null,
    password_hash varchar(255) not null,
    role          varchar(255) not null
        constraint admins_role_check
            check ((role)::text = 'ADMIN'::text)
);

alter table admins
    owner to postgres;

create table if not exists  cities
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    is_active  boolean      not null,
    name_en    varchar(100) not null,
    name_ru    varchar(100) not null
);

alter table cities
    owner to postgres;

create table if not exists  refresh_tokens
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    expiry_date timestamp(6) not null,
    revoked     boolean      not null,
    token       varchar(255) not null
        constraint ukghpmfn23vmxfu3spu3lfg4r2d
            unique,
    admin_id    bigint       not null
        constraint fkq8cwpf4th3ejkj8a82gbois1u
            references admins
);

alter table refresh_tokens
    owner to postgres;

create table if not exists  social_tasks
(
    id         integer generated by default as identity
        primary key,
    channel_id varchar(255),
    created_at timestamp(6) not null,
    is_active  boolean      not null,
    link       varchar(500) not null,
    reward     integer      not null,
    title      varchar(255) not null,
    type       varchar(255) not null
        constraint social_tasks_type_check
            check ((type)::text = ANY
                   ((ARRAY ['TELEGRAM'::character varying, 'INSTAGRAM'::character varying, 'FACEBOOK'::character varying, 'TIKTOK'::character varying, 'YOUTUBE'::character varying])::text[]))
);

alter table social_tasks
    owner to postgres;

create table if not exists  users
(
    id            bigint generated by default as identity
        primary key,
    balance       integer      not null,
    created_at    timestamp(6) not null,
    first_name    varchar(255),
    is_banned     boolean      not null,
    language      varchar(255) not null
        constraint users_language_check
            check ((language)::text = ANY
                   ((ARRAY ['RU'::character varying, 'KY'::character varying, 'EN'::character varying])::text[])),
    last_name     varchar(255),
    phone         varchar(20)  not null,
    referral_code varchar(50)
        constraint ukdb3w2sgtsy1kf0qitc77h0bpa
            unique,
    telegram_id   bigint       not null
        constraint ukdus03vmwyluiy7k2p2gcrqbms
            unique,
    updated_at    timestamp(6),
    username      varchar(255),
    referrer_id   bigint
        constraint fkhkoxvfxs6cnk8iu3d90kel70r
            references users
);

alter table users
    owner to postgres;

create table  if not exists chat_messages
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) not null,
    message_text        text,
    message_type        varchar(255)
        constraint chat_messages_message_type_check
            check ((message_type)::text = ANY
                   ((ARRAY ['TEXT'::character varying, 'COMMAND'::character varying, 'PHOTO'::character varying, 'DOCUMENT'::character varying, 'LOCATION'::character varying, 'CONTACT'::character varying])::text[])),
    sender_type         varchar(255) not null
        constraint chat_messages_sender_type_check
            check ((sender_type)::text = ANY ((ARRAY ['USER'::character varying, 'BOT'::character varying])::text[])),
    telegram_message_id bigint,
    user_id             bigint       not null
        constraint fk6f0y4l43ihmgfswkgy9yrtjkh
            references users
);

alter table chat_messages
    owner to postgres;

create table  if not exists feedback
(
    id             bigint generated by default as identity
        primary key,
    admin_response text,
    answered_at    timestamp(6),
    created_at     timestamp(6) not null,
    message        text         not null,
    status         varchar(255) not null
        constraint feedback_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ANSWERED'::character varying])::text[])),
    answered_by    bigint
        constraint fk9n42j4gqxo1kp5iqcayannkjj
            references admins,
    user_id        bigint       not null
        constraint fkpwwmhguqianghvi1wohmtsm8l
            references users
);

alter table feedback
    owner to postgres;

create table  if not exists payments
(
    id             bigint generated by default as identity
        primary key,
    amount         numeric(10, 2) not null,
    completed_at   timestamp(6),
    created_at     timestamp(6)   not null,
    payment_id     varchar(255)   not null
        constraint ukt4ffsaqe8d6i83gs100u2y3l1
            unique,
    payment_url    text,
    plan_type      varchar(255)
        constraint payments_plan_type_check
            check ((plan_type)::text = ANY
                   ((ARRAY ['THREE_DAYS'::character varying, 'ONE_WEEK'::character varying, 'ONE_MONTH'::character varying, 'THREE_MONTHS'::character varying])::text[])),
    receipt_number varchar(255),
    status         varchar(255)   not null
        constraint payments_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'EXPIRED'::character varying])::text[])),
    transaction_id varchar(255)
        constraint uklryndveuwa4k5qthti0pkmtlx
            unique,
    user_id        bigint
        constraint fkj94hgy9v5fw1munb90tar2eje
            references users
);

alter table payments
    owner to postgres;

create table  if not exists  points_transactions
(
    id          bigint generated by default as identity
        primary key,
    amount      integer      not null,
    created_at  timestamp(6) not null,
    description varchar(255),
    related_id  bigint,
    type        varchar(255) not null
        constraint points_transactions_type_check
            check ((type)::text = ANY
                   ((ARRAY ['REFERRAL'::character varying, 'TASK'::character varying, 'SEARCH_ACCESS'::character varying, 'ADMIN_GRANT'::character varying, 'REGISTRATION'::character varying, 'SUBSCRIPTION'::character varying, 'REFUND'::character varying, 'WITHDRAWAL'::character varying, 'BOOST'::character varying])::text[])),
    user_id     bigint       not null
        constraint fkepyf6igu2l1nu69knrg7gklnk
            references users
);

alter table points_transactions
    owner to postgres;

create table  if not exists subscriptions
(
    id               bigint generated by default as identity
        primary key,
    created_at       timestamp(6) not null,
    end_date         timestamp(6) not null,
    is_active        boolean      not null,
    payment_id       varchar(255),
    plan_type        varchar(255) not null
        constraint subscriptions_plan_type_check
            check ((plan_type)::text = ANY
                   ((ARRAY ['THREE_DAYS'::character varying, 'ONE_WEEK'::character varying, 'ONE_MONTH'::character varying, 'THREE_MONTHS'::character varying])::text[])),
    start_date       timestamp(6) not null,
    granted_by_admin bigint
        constraint fki8rhw704606md8o49beyd2aut
            references admins,
    user_id          bigint       not null
        constraint fkhro52ohfqfbay9774bev0qinr
            references users
);

alter table subscriptions
    owner to postgres;

create table  if not exists user_tasks
(
    id           bigint generated by default as identity
        primary key,
    completed_at timestamp(6) not null,
    reward_given integer      not null,
    task_id      integer      not null
        constraint fk696griw3jgqw818t71yuibsu5
            references social_tasks,
    user_id      bigint       not null
        constraint fksrpyfa9asu2ymkcqr7jol85o2
            references users,
    constraint uki5ghi37rrld7pu0pjtxt5s1h9
        unique (user_id, task_id)
);

alter table user_tasks
    owner to postgres;

create table if not exists  withdrawals
(
    id                    bigint generated by default as identity
        primary key,
    account_id            varchar(255)   not null,
    amount                numeric(38, 2) not null,
    completed_at          timestamp(6),
    created_at            timestamp(6)   not null,
    error_message         varchar(1000),
    finik_transaction_id  varchar(255),
    points_transaction_id bigint,
    recipient_name        varchar(255),
    recipient_phone       varchar(255)   not null,
    service_id            varchar(255)   not null,
    service_name          varchar(255),
    status                varchar(255)   not null
        constraint withdrawals_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'PROCESSING'::character varying, 'SUCCEEDED'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying])::text[])),
    transaction_id        varchar(255)   not null
        constraint ukgobjdu1smp3tye22ir0bo8w7x
            unique,
    user_id               bigint         not null
        constraint fkesk6migh8b3x43q3740dh5fja
            references users
);

alter table withdrawals
    owner to postgres;

create table  if not exists spheres
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    is_active  boolean      not null,
    name_en    varchar(100) not null,
    name_ky    varchar(100) not null,
    name_ru    varchar(100) not null
);

alter table spheres
    owner to postgres;

create table  if not exists categories
(
    id         integer generated by default as identity
        primary key,
    created_at timestamp(6) not null,
    icon       varchar(10),
    is_active  boolean      not null,
    name_en    varchar(100) not null,
    name_ky    varchar(100) not null,
    name_ru    varchar(100) not null,
    sphere_id  integer
        constraint fke60251p7imcgbbecjpyyh0a6h
            references spheres
);

alter table categories
    owner to postgres;

create table if not exists  subcategories
(
    id          integer generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    is_active   boolean      not null,
    name_en     varchar(100) not null,
    name_ky     varchar(100) not null,
    name_ru     varchar(100) not null,
    category_id integer      not null
        constraint fkiborb6ptvy1t1n3v6klb56l5s
            references categories
);

alter table subcategories
    owner to postgres;

create table  if not exists resumes
(
    id             bigint generated by default as identity
        primary key,
    age            integer,
    created_at     timestamp(6) not null,
    description    text,
    experience     integer,
    gender         varchar(255)
        constraint resumes_gender_check
            check ((gender)::text = ANY ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying])::text[])),
    is_active      boolean      not null,
    name           varchar(255) not null,
    updated_at     timestamp(6),
    category_id    integer      not null
        constraint fk9tycht3v4aptbittllhh5h99x
            references categories,
    city_id        integer      not null
        constraint fkkwuft5eo0bgtael6qvj496cx3
            references cities,
    subcategory_id integer      not null
        constraint fk73m9dit33hu3dtrnr0x635lo7
            references subcategories,
    user_id        bigint       not null
        constraint fk340nuaivxiy99hslr3sdydfvv
            references users
);

alter table resumes
    owner to postgres;

create table  if not exists resume_boosts
(
    id           bigint generated by default as identity
        primary key,
    amount_paid  integer,
    boost_date   timestamp(6) not null,
    created_at   timestamp(6) not null,
    expires_at   timestamp(6) not null,
    is_active    boolean      not null,
    payment_id   varchar(255),
    payment_type varchar(255) not null
        constraint resume_boosts_payment_type_check
            check ((payment_type)::text = ANY
                   ((ARRAY ['POINTS'::character varying, 'MONEY'::character varying])::text[])),
    resume_id    bigint       not null
        constraint fkhlbjcyxasoff5p5h9nyhhcc5g
            references resumes,
    user_id      bigint       not null
        constraint fkm311lpsnmkevj5dg8nqnwdpby
            references users
);

alter table resume_boosts
    owner to postgres;

create table  if not exists resume_statistics
(
    id                   bigint generated by default as identity
        primary key,
    contact_clicks_count bigint       not null,
    created_at           timestamp(6) not null,
    invitation_count     bigint       not null,
    last_view_at         timestamp(6),
    views_count          bigint       not null,
    resume_id            bigint       not null
        constraint ukcad8bt7nxl8b0qmgkhrentt0c
            unique
        constraint fkp6ikj3qlh52bab45eqdco2gpv
            references resumes
);

alter table resume_statistics
    owner to postgres;

create table  if not exists vacancies
(
    id                 bigint generated by default as identity
        primary key,
    address            varchar(255),
    company_name       varchar(255),
    created_at         timestamp(6) not null,
    description        text,
    experience_in_year integer,
    is_active          boolean      not null,
    max_age            integer,
    min_age            integer,
    phone              varchar(20),
    preferred_gender   varchar(255)
        constraint vacancies_preferred_gender_check
            check ((preferred_gender)::text = ANY
                   ((ARRAY ['MALE'::character varying, 'FEMALE'::character varying, 'ANY'::character varying])::text[])),
    salary             varchar(100),
    schedule           varchar(255),
    title              varchar(255) not null,
    updated_at         timestamp(6),
    category_id        integer      not null
        constraint fkpjhcgh8h8mfxaah37dk13s4b2
            references categories,
    city_id            integer      not null
        constraint fk4wyvjd3uld76oi38rai43h66n
            references cities,
    subcategory_id     integer      not null
        constraint fkhfyp4dm0mmfg5ki66oxpb4spk
            references subcategories,
    user_id            bigint       not null
        constraint fklk4s3j11s10gc7biicj1xocoq
            references users
);

alter table vacancies
    owner to postgres;

create table  if not exists resume_invitations
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) not null,
    message     text,
    status      varchar(255) not null
        constraint resume_invitations_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'VIEWED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])),
    viewed_at   timestamp(6),
    employer_id bigint       not null
        constraint fkrtlxiwi06ptop5o3dvat91dko
            references users,
    resume_id   bigint       not null
        constraint fkmopy7sxau87tcx4weieufbyrb
            references resumes,
    vacancy_id  bigint       not null
        constraint fkd8o6udfocf2w1kjh5b4jdggdb
            references vacancies,
    constraint uk5xh4oi6t1ts0hd2s0bioifnt9
        unique (resume_id, vacancy_id)
);

alter table resume_invitations
    owner to postgres;

create table  if not exists vacancy_boosts
(
    id           bigint generated by default as identity
        primary key,
    amount_paid  integer,
    boost_date   timestamp(6) not null,
    created_at   timestamp(6) not null,
    expires_at   timestamp(6) not null,
    is_active    boolean      not null,
    payment_id   varchar(255),
    payment_type varchar(255) not null
        constraint vacancy_boosts_payment_type_check
            check ((payment_type)::text = ANY
                   ((ARRAY ['POINTS'::character varying, 'MONEY'::character varying])::text[])),
    user_id      bigint       not null
        constraint fk6tlrobhqonvnj78qarlepykd8
            references users,
    vacancy_id   bigint       not null
        constraint fk6mugigfv7wmqdjak9dbwp0pkf
            references vacancies
);

alter table vacancy_boosts
    owner to postgres;

create table  if not exists vacancy_responses
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) not null,
    message      text,
    status       varchar(255) not null
        constraint vacancy_responses_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'VIEWED'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])),
    viewed_at    timestamp(6),
    applicant_id bigint       not null
        constraint fkfc2wi7du3o6bbe1nn355ckswb
            references users,
    resume_id    bigint       not null
        constraint fkqiw2reix88w7oend0ixe8c2k5
            references resumes,
    vacancy_id   bigint       not null
        constraint fk535515d7bn71s5u0r80s8f7f1
            references vacancies,
    constraint ukkqbs306js5vjm5w7ckgop0ufi
        unique (vacancy_id, resume_id)
);

alter table vacancy_responses
    owner to postgres;

create table  if not exists vacancy_reviews
(
    id         bigint generated by default as identity
        primary key,
    comment    text,
    created_at timestamp(6) not null,
    is_spam    boolean      not null,
    rating     integer      not null,
    updated_at timestamp(6),
    user_id    bigint       not null
        constraint fk3c72afaaq491v6707kumlol01
            references users,
    vacancy_id bigint       not null
        constraint fk6pojfeq2ry6tndbwlxsutuda2
            references vacancies,
    constraint uktjj602d75fqq99gewuypwhdf1
        unique (vacancy_id, user_id)
);

alter table vacancy_reviews
    owner to postgres;

create table  if not exists vacancy_statistics
(
    id                   bigint generated by default as identity
        primary key,
    contact_clicks_count bigint       not null,
    created_at           timestamp(6) not null,
    last_view_at         timestamp(6),
    response_count       bigint       not null,
    views_count          bigint       not null,
    vacancy_id           bigint       not null
        constraint uk42l18npl7badkea4b4mtau1fr
            unique
        constraint fk2h1xeq6rkmckq5c8tdq8pfd0v
            references vacancies
);

alter table vacancy_statistics
    owner to postgres;

